export const questions = [
    "Held hands romantically?",
    "Been on a date?",
    "Been in a relationship?",
    "Danced without leaving room for Jesus?",
    "Kissed a non-family member?",
    "Kissed on the lips?",
    "French kissed?",
    "French kissed in public?",
    "Kissed on the neck?",
    "Kissed horizontally?",
    "Given or received a hickey?",
    "Kissed or been kissed on the breast?",
    "Kissed someone below the belt?",
    "Kissed for more than two hours consecutively?",
    "Played strip poker?",
    "Seen or been seen by another person in a sensual context?",
    "Masturbated?",
    "Masturbated to a picture or video?",
    "Been caught masturbating?",
    "Masturbaed with an inanimate object?",
    "Seen or read pornographic material?",
    "Watched R rated movies?",
    "Been caught watching porn?",
    "Purchased pornographic material?",
    "Watched porn with others?",
    "Engaged in cybersex?",
    "Sent or received sexually explicit photographs?",
    "Sent or received a nude photo?",
    "Been inappropriate sexually in public?",
    "Had sexual intercourse?",
    "Had sexual intercourse three or more times in one night?",
    "Had sexual intercourse 10 or more times?",
    "Had sexual intercourse in four or more positions?",
    "Had sexual intercourse in a motor vehicle?",
    "Had sexual intercourse outdoors?",
    "Had sexual intercourse in public?",
    "Had sexual intercourse in a swimming pool or hot tub?",
    "Had sexual intercourse in a bed not your own?",
    "Had sexual intercourse while someone else was in the same room?",
    "Had sexual intercourse with a stranger?",
    "Had sexual intercourse with a person you met on the internet?",
    "Had sexual intercourse on the first date?",
    "Had sexual intercourse with more than one person in 24 hours?",
    "Had sexual intercourse with someone you don't know the name of?",
    "Had sexual intercourse with someone at least 5 years older or younger?",
    "Been photographed or filmed during sexual intercourse?",
    "Cheated on a significant other during a relationship?",
    "Helped someone cheat on a significant other?",
    "Engaged in bestiality?",
    "Paid or been paid for a sexual act?",
    "Committed an act of voyeurism?",
    "Committed an act of incest?",
    "Engaged in sexual activity with someone of the same gender?",
    "Used marijuana?",
    "Used cocaine?",
    "Used heroin?",
    "Used methamphetamine?",
    "Used ecstasy?",
    "Used PCP?",
    "Used LSD?",
    "Used mushrooms?",
    "Used ketamine?",
    "Used nitrous oxide?",
    "Used GHB?",
    "Used prescription drugs for recreational purposes?",
    "Been sent to the office of a principal, dean or judicial affairs representative for a disciplinary infraction?",
    "Been put on disciplinary probation or suspended?",
    "Urinated in public?",
    "Gone skinny-dipping?",
    "Streaked?",
    "Seen a stripper?",
    "Had the police called on you?",
    "Run from the police?",
    "Had the police handcuff you?",
    "Been arrested?",
    "Been convicted of a crime?",
    "Been convicted of a felony?",
    "Committed an act of vandalism?",
    "Had sexual intercourse while under the influence of alcohol or drugs?",
    "Been suspended from school?",
    "Had sex in a church?",
    "Thrown up from drinking?",
    "Played a drinking game?",
    "Been drunk at school?",
    "Been drunk in public?",
    "Blacked out from drinking?",
    "Faked sobriety to authority?",
    "Had a hangover?",
    "Used tobacco?",
    "Used alcohol?",
    "Used drugs?",
    "Been sent to rehab?",
    "Bought cigarettes?",
    "Bought alcohol?",
    "Bought drugs?",
    "Used a fake ID?",
    "Snuck out of your parents' house?",
    "Snuck into a club or bar?",
    "Snuck somebody into your house?",
    "Been to a strip club?",
    "Been kicked out of a bar/club?",
    "Had a one night stand?",
    "Had sex with someone whose name you didn't know?",
    "Had sex with someone you met at a bar/club?",
    "Been in a fight?",
    "Been mugged?",
    "Shoplifted?",
    "Stolen anything?",
    "Broken into someplace?",
    "Vandalized property?"
  ] as const;